services:

  redis:
    image: redis:7-alpine
    container_name: bytelog-redis
    restart: unless-stopped

    ports: 
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10


  backend:
    build:
      context: ./backend

    container_name: bytelog-backend

    restart: unless-stopped

    env_file:
      - ./backend/.env

    environment:
      IS_DOCKER: "true"

    ports:
      - "8002:8002"

    volumes:
      - ./backend/public/temp:/app/public/temp

    depends_on:
      redis:
        condition: service_healthy

    command: npm start


  blog-worker:
    build:
      context: ./backend

    container_name: bytelog-blog-worker

    restart: unless-stopped

    env_file:
      - ./backend/.env

    environment:
      IS_DOCKER: "true"

    volumes:
      - ./backend/public/temp:/app/public/temp

    depends_on:
      redis:
        condition: service_healthy

    command: npm run worker:blog


  like-worker:
    build:
      context: ./backend

    container_name: bytelog-like-worker

    restart: unless-stopped

    env_file:
      - ./backend/.env

    environment:
      IS_DOCKER: "true"

    depends_on:
      redis:
        condition: service_healthy

    command: npm run worker:like


volumes:
  redis_data: